kind: ReplicationController
apiVersion: v1
metadata:
    name: mysql-rc-master
spec:
    replicas: 1
    selector:
        name: mysql-master
        role: mysql
        environment: test
    template:
        spec:
          containers:
            - name: mysql-master
              image: gcr.io/mcc-2016-g17-p2/mysql-master:latest
              env:
                - name: MYSQL_USER
                  value: "mysql"
                - name: MYSQL_PASSWORD
                  value: "mysql"
                - name: MYSQL_DATABASE
                  value: "sample"
                - name: MYSQL_ROOT_PASSWORD
                  value: "root"
                - name: MYSQL_REPLICATION_PASSWORD
                  value: "repl"
              ports:
                - containerPort: 3306
              volumeMounts:
                  - name: mysql-storage-master
                    mountPath: /var/lib/mysql/data
          volumes:
          - name: mysql-storage-master
            gcePersistentDisk:
                pdName: mysql-disk-1
                fsType: ext4
        metadata:
            labels:
                name: mysql-master
                role: mysql
                environment: test
