apiVersion: v1
kind: Service
metadata:
    labels:
        name: mysql-svc-master
    name: mysql-svc-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: mysql-master
